# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---


# Gather facts if we don't already have them.  This step
# is required in order to be able to specify tags at runtime
- name: Gather facts
  become: true
  ansible.builtin.setup:
  tags: ['always']
  when: ansible_facts == {}


# Configure /etc/issue
- name: Configure /etc/issue
  become: true
  ansible.builtin.template:
    src: 'etc/issue.j2'
    dest: '/etc/issue'
    owner: 'root'
    group: 'root'
    mode: '0644'


# Configure /etc/issue
- name: Configure /etc/issue
  become: true
  ansible.builtin.template:
    src: 'etc/issue.j2'
    dest: '/etc/issue'
    owner: 'root'
    group: 'root'
    mode: '0644'


# Configure /etc/motd
- name: Configure /etc/motd
  become: true
  ansible.builtin.template:
    src: 'etc/motd.j2'
    dest: '/etc/motd'
    owner: 'root'
    group: 'root'
    mode: '0644'


# Flush any handlers that we might have called
- name: Flush handlers
  ansible.builtin.meta:
    flush_handlers
