# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/banner
  block:

    - name: Configure /etc/issue
      become: true
      ansible.builtin.template:
        src: 'etc/issue.j2'
        dest: '/etc/issue'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Configure /etc/issue.net
      become: true
      ansible.builtin.template:
        src: 'etc/issue.j2'
        dest: '/etc/issue.net'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Configure /etc/motd
      become: true
      ansible.builtin.template:
        src: 'etc/motd.j2'
        dest: '/etc/motd'
        owner: 'root'
        group: 'root'
        mode: '0644'

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_banner'
